---
title: 
output: 
    html_document:
       theme: yeti
---

<style>
.darkgreen {
  background-color: #577836;
  color: white;
  border: 2px solid black;
  margin: 20px;
  padding: 20px;
} 
  li {
    list-style-type: none
  }
</style>

<style>
    body { 
            background-color: #4D251C;
            text-color: whitesmoke;
            color: whitesmoke;
            font-family: Palatino;
            font-size: 12pt;
            margin: 20px;
            padding: 20px;
            }
   a:link {
            color: #577836; 
            background-color: transparent; 
            }
  a:visited {
            color: #577836;
            background-color: transparent;
          }
  a:active {
    color: #577836;
    background-color: transparent;
  }
  a:hover {
    color: #577836;
    background-color: transparent;
    text-decoration: underline;
  }
</style>

<style>
.darkblue {
  background-color: #262C56;
  color: white;
  border: 2px solid #577836;
  margin: 20px;
  padding:20px;
} 
</style>

<br>

<center> <h1> rebalancedcv.**RebalancedKFold** </h1> </center>


```{r klippy, echo=FALSE, include=TRUE}
klippy::klippy(c('r', 'python', 'bash'), 
               position = c("top", "right"),
               color='brown',
               tooltip_message = "Copy",
               tooltip_success = "Copied!"
               )
```

<style>
.darkgrey {
  background-color: #333333;
  color: white;
  border: 2px solid #577836;
  margin: 20px;
  padding:10px;
} 
</style>
<div class="darkgrey">
*class* rebalancedcv.**RebalancedKFold**(n_splits=5, shuffle=False, random_state=None)
</div>
<br>

Description
------------

<div class="darkgreen">

Stratified K-Fold cross-validator with rebalancing.

Provides train/test indices to split data in train/test sets, with sub-sampling within the training set to ensure that all training folds have identical class balances.

This class is designed to have the same functionality and 
implementation structure as scikit-learn's ```StratifiedKFold```.

</div>

<br>

Parameters
-----------

<div class="darkgreen">
* <b>n_splits : int, default=5</b>
  * Number of folds. Must be at least 2.
* <hr style="height: 2.5px; background-color: white; margin: 1px">
* <b>shuffle : bool, default=False</b>
  * Whether to shuffle each class's samples before splitting into batches. Note that the samples within each split will not be shuffled.
* <hr style="height: 2.5px; background-color: white; margin: 1px">
* <b>random_state : int, RandomState instance or None, default=None</b>
  * When `shuffle` is True, `random_state` affects the ordering of the
        indices, which controls the randomness of each fold for each class.
        Otherwise, leave `random_state` as `None`.
        Pass an int for reproducible output across multiple function calls.
        See :term:`Glossary <random_state>`.
</div>
These parameters are designed to match the structure and functionality of scikit-learn's `StratifiedKFold`. 





Example
--------

```python
### Observing the indices on a small example dataset
import numpy as np
from rebalancedcv import RebalancedKFold

X = np.array([[1, 2, 1, 2, 1], [3, 4, 3, 4, 3]]).T
y = np.array([1, 2, 1, 2, 1])
rloo = RebalancedKFold(n_splits=2)
rloo.get_n_splits(X, y)
for i, (train_index, test_index) in enumerate(rloo.split(X, y)):
    print(f"Fold {i}:")
    print(f"  Train: index={train_index}")
    print(f"  Test:  index={test_index}")
```

    Fold 0:
      Train: index=[3 4]
      Test:  index=[0 1 2]
    Fold 1:
      Train: index=[0 1]
      Test:  index=[3 4]
<br>

Methods
--------

The methods of the `RebalancedLeavePOut` class are designed to enable identical funcitonality to scikit-learn's [`LeavePOut`](https://scikit-learn.org/stable/modules/generated/sklearn.model_selection.LeavePOut.html).

<div class="darkgreen">
<b>split(X, y, groups=None, seed=None)</b> 
<hr style="height: 2.5px; background-color: white; margin: 1px">
* Generate indices to split data into training and test set.
* <hr style="height: 2.5px; background-color: white; margin: 1px">
  * <u><b>Parameters</b></u>
    *  <b>X : array-like of shape (n_samples, n_features)</b>
      * Training data, where `n_samples` is the number of samples and `n_features` is the number of features.
    * <b>y : array-like of shape (n_samples,)</b>
      * The target variable for supervised learning problems.
    * <b>groups : array-like of shape (n_samples,), default=None</b>
      * Group labels for the samples used while splitting the dataset into train/test set.
    * <b>seed : int, default=None</b>
      * If provided, is used to set a seed in subsampling
  * <hr style="height: 2.5px; background-color: white; margin: 1px">
  * <u><b>Yields</b></u>
    * <b>train : ndarray</b>
      * The training set indices for that split.
    * <b>test : ndarray</b>
      * The testing set indices for that split.    
</div>


<style>
.seealso {
  background-color: #F6B302;
  color: black;
  border: 2px solid black;
  margin: 20px;
  padding: 20px;
} 

l{color: darkgreen}
</style>


<div class="seealso">
**See also:**<br>
[__RebalancedLeaveOneOut__](RebalancedLeaveOneOut.html)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
Leave-one-out iterator with training set rebalancing<br>
[__RebalancedLeavePOut__](RebalancedLeavePOut.html)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
Leave-P-out iterator with training set rebalancing<br>
<br>
For more background on Stratified K-Fold, refer to the scikit-learn [User Guide](https://scikit-learn.org/stable/modules/cross_validation.html#k-fold).
    </div>
